// Generated by wrangler types or manually defined
// Run: wrangler types

interface Env {
  // D1 Database
  DB: D1Database;

  // R2 Bucket
  ATTACHMENTS: R2Bucket;

  // Queues
  DELIVERY_QUEUE: Queue;
  DELIVERY_DLQ: Queue;

  // KV Namespace
  KV: KVNamespace;

  // Environment Variables
  ENVIRONMENT: string;
  APP_NAME: string;

  // Secrets (set via wrangler secret put)
  TWITTER_API_KEY?: string;
  TWITTER_API_SECRET?: string;
  TWITTER_ACCESS_TOKEN?: string;
  TWITTER_ACCESS_TOKEN_SECRET?: string;
  SENDGRID_API_KEY?: string;
  TWILIO_ACCOUNT_SID?: string;
  TWILIO_AUTH_TOKEN?: string;
  COOKIE_SECRET?: string;
}
