/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as IndexRouteImport } from './routes/index'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/messages': typeof MessagesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/incidents'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/subscribers'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incidents'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/subscribers'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/incidents'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/subscribers'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsRoute: typeof IncidentsRoute
  MessagesRoute: typeof MessagesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SubscribersRoute: typeof SubscribersRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsRoute: IncidentsRoute,
  MessagesRoute: MessagesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SubscribersRoute: SubscribersRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
