/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesNewRouteImport } from './routes/messages/new'
import { Route as MessagesMessageIdRouteImport } from './routes/messages/$messageId'
import { Route as IncidentsNewRouteImport } from './routes/incidents/new'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents/$incidentId'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesNewRoute = MessagesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesMessageIdRoute = MessagesMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => MessagesRoute,
} as any)
const IncidentsNewRoute = IncidentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IncidentsRoute,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/$incidentId',
  path: '/$incidentId',
  getParentRoute: () => IncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRoute
  '/templates': typeof TemplatesRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/new': typeof IncidentsNewRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/new': typeof MessagesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRoute
  '/templates': typeof TemplatesRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/new': typeof IncidentsNewRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/new': typeof MessagesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRoute
  '/templates': typeof TemplatesRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/incidents/new': typeof IncidentsNewRoute
  '/messages/$messageId': typeof MessagesMessageIdRoute
  '/messages/new': typeof MessagesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/incidents'
    | '/login'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/subscribers'
    | '/templates'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/messages/$messageId'
    | '/messages/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/incidents'
    | '/login'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/subscribers'
    | '/templates'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/messages/$messageId'
    | '/messages/new'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/incidents'
    | '/login'
    | '/messages'
    | '/reports'
    | '/settings'
    | '/subscribers'
    | '/templates'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/messages/$messageId'
    | '/messages/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SubscribersRoute: typeof SubscribersRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/new': {
      id: '/messages/new'
      path: '/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof MessagesNewRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$messageId': {
      id: '/messages/$messageId'
      path: '/$messageId'
      fullPath: '/messages/$messageId'
      preLoaderRoute: typeof MessagesMessageIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/incidents/new': {
      id: '/incidents/new'
      path: '/new'
      fullPath: '/incidents/new'
      preLoaderRoute: typeof IncidentsNewRouteImport
      parentRoute: typeof IncidentsRoute
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
  }
}

interface IncidentsRouteChildren {
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  IncidentsNewRoute: typeof IncidentsNewRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  IncidentsNewRoute: IncidentsNewRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

interface MessagesRouteChildren {
  MessagesMessageIdRoute: typeof MessagesMessageIdRoute
  MessagesNewRoute: typeof MessagesNewRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesMessageIdRoute: MessagesMessageIdRoute,
  MessagesNewRoute: MessagesNewRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SubscribersRoute: SubscribersRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
